# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Untitled Technoblog
email: jarrod.carlson@gmail.com
description: >
  I do code stuff. And I talk about it here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jcarlson.github.io" # the base hostname & protocol for your site
twitter_username: jcarlsonuga
github_username:  jcarlson

# Build settings
markdown: kramdown

gems:
  - octopress-debugger
